GEM5_DIR ?= /home/yangfan/plct-gem5/
vwred:
	${GEM5_DIR}build/RISCV/gem5.opt  --debug-flags=ExecAll ${GEM5_DIR}/configs/example/se.py \
	--cmd="./rv64uv-ps-vwredsumu.vs_LMUL1SEW16" --cpu-type=O3CPU --caches